Lint/UselessAssignment:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
Style/EachWithObject:
  Enabled: false
Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - z
    - i
    - n
    - dx
    - dy
Style/ParallelAssignment:
  Enabled: false